orbs:
  aws-code-deploy: circleci/aws-code-deploy@1.0.1
version: 2.1
workflows:
  deploy_application:
    jobs:
      - aws-code-deploy/deploy:
          application-name: myApplication
          bundle-bucket: myApplicationS3Bucket
          bundle-key: myS3BucketKey
          deployment-group: myDeploymentGroup
          service-role-arn: myDeploymentGroupRoleARN
override_credentials:
    description: |
      Deploy an application to AWS CodeDeploy with specific aws profile
    usage:
      orbs:
        aws-code-deploy: circleci/aws-code-deploy@1.0.1
      version: 2.1
      workflows:
        deploy_application:
          jobs:
          - aws-code-deploy/deploy:
              application-name: myApplication
              arguments: --profile assume_role
              bundle-bucket: myApplicationS3Bucket
              bundle-key: myS3BucketKey
              deployment-group: myDeploymentGroup
              service-role-arn: myDeploymentGroupRoleARN
